/* Simscape target specific file.
 * This file is generated for the Simscape network associated with the solver block 'shell_elec_electric_vehicle/Solver Configuration'.
 */

#include "ne_ds.h"
#include "shell_elec_electric_vehicle_442b803b_1_ds_slf.h"
#include "shell_elec_electric_vehicle_442b803b_1_ds_ds_struct.h"
#include "shell_elec_electric_vehicle_442b803b_1_ds_externals.h"
#include "shell_elec_electric_vehicle_442b803b_1_ds_external_struct.h"

int32_T shell_elec_electric_vehicle_442b803b_1_ds_slf(const NeDynamicSystem *ds,
  const NeDynamicSystemInput *t1, NeDsMethodOutput *t2)
{
  PmBoolVector out;
  (void)t1;
  out = t2->mSLF;
  out.mX[0] = false;
  out.mX[1] = false;
  out.mX[2] = false;
  out.mX[3] = false;
  out.mX[4] = false;
  out.mX[5] = false;
  out.mX[6] = false;
  out.mX[7] = false;
  out.mX[8] = false;
  out.mX[9] = false;
  out.mX[10] = false;
  out.mX[11] = false;
  out.mX[12] = false;
  out.mX[13] = false;
  out.mX[14] = false;
  out.mX[15] = false;
  out.mX[16] = false;
  out.mX[17] = false;
  out.mX[18] = false;
  out.mX[19] = false;
  out.mX[20] = false;
  out.mX[21] = false;
  out.mX[22] = false;
  out.mX[23] = false;
  out.mX[24] = false;
  out.mX[25] = false;
  out.mX[26] = false;
  out.mX[27] = false;
  out.mX[28] = false;
  out.mX[29] = false;
  out.mX[30] = false;
  out.mX[31] = false;
  out.mX[32] = false;
  out.mX[33] = false;
  out.mX[34] = false;
  out.mX[35] = false;
  out.mX[36] = false;
  out.mX[37] = false;
  out.mX[38] = false;
  out.mX[39] = false;
  out.mX[40] = false;
  out.mX[41] = false;
  out.mX[42] = false;
  out.mX[43] = false;
  out.mX[44] = false;
  out.mX[45] = false;
  out.mX[46] = false;
  out.mX[47] = false;
  out.mX[48] = false;
  out.mX[49] = false;
  out.mX[50] = false;
  out.mX[51] = false;
  out.mX[52] = false;
  out.mX[53] = false;
  out.mX[54] = false;
  out.mX[55] = false;
  out.mX[56] = false;
  out.mX[57] = false;
  out.mX[58] = false;
  out.mX[59] = false;
  out.mX[60] = false;
  out.mX[61] = false;
  out.mX[62] = false;
  out.mX[63] = false;
  out.mX[64] = false;
  out.mX[65] = false;
  out.mX[66] = false;
  out.mX[67] = false;
  out.mX[68] = false;
  out.mX[69] = false;
  out.mX[70] = false;
  out.mX[71] = false;
  out.mX[72] = false;
  out.mX[73] = false;
  out.mX[74] = false;
  out.mX[75] = false;
  out.mX[76] = false;
  out.mX[77] = false;
  out.mX[78] = false;
  out.mX[79] = false;
  out.mX[80] = false;
  out.mX[81] = false;
  out.mX[82] = false;
  out.mX[83] = false;
  out.mX[84] = false;
  out.mX[85] = false;
  out.mX[86] = false;
  out.mX[87] = false;
  out.mX[88] = false;
  out.mX[89] = false;
  out.mX[90] = false;
  out.mX[91] = false;
  out.mX[92] = false;
  out.mX[93] = false;
  out.mX[94] = false;
  out.mX[95] = false;
  out.mX[96] = false;
  out.mX[97] = false;
  out.mX[98] = false;
  out.mX[99] = false;
  out.mX[100] = false;
  out.mX[101] = false;
  out.mX[102] = false;
  out.mX[103] = false;
  out.mX[104] = false;
  out.mX[105] = false;
  out.mX[106] = false;
  out.mX[107] = false;
  out.mX[108] = false;
  out.mX[109] = false;
  out.mX[110] = false;
  out.mX[111] = false;
  out.mX[112] = false;
  out.mX[113] = false;
  out.mX[114] = false;
  out.mX[115] = false;
  out.mX[116] = false;
  out.mX[117] = false;
  out.mX[118] = false;
  out.mX[119] = false;
  out.mX[120] = false;
  out.mX[121] = false;
  out.mX[122] = false;
  out.mX[123] = false;
  out.mX[124] = false;
  out.mX[125] = false;
  out.mX[126] = false;
  out.mX[127] = false;
  out.mX[128] = false;
  out.mX[129] = false;
  (void)ds;
  (void)t2;
  return 0;
}
